---
abstract: 'Retrieve and reparse the Win32 command line'
author:
  - 'Roy Ivy III <rivy@cpan.org>'
build_requires:
  CPAN::Meta: '0'
  Carp: '0'
  Config: '0'
  Cwd: '0'
  ExtUtils::CBuilder: '0'
  ExtUtils::Manifest: '1.54'
  File::Basename: '0'
  File::Find: '0'
  File::Glob: '0'
  File::Path: '0'
  File::Spec: '0'
  File::Spec::Functions: '0'
  File::Which: '0'
  FindBin: '0'
  IO::File: '0'
  IPC::Run3: '0'
  Module::Build: '0'
  Probe::Perl: '0'
  TAP::Formatter::Color: '0'
  TAP::Formatter::Console: '0'
  TAP::Harness: '0'
  Test::CPAN::Meta: '0'
  Test::CPAN::Meta::JSON: '0'
  Test::Differences: '0'
  Test::More: '0'
  Text::Template: '1.44'
  URI: '0'
  perl: v5.6.1
  version: '0.77'
configure_requires:
  Config: '0'
  Cwd: '0'
  ExtUtils::Manifest: '1.54'
  File::Basename: '0'
  File::Find: '0'
  File::Glob: '0'
  File::Path: '0'
  File::Spec: '0'
  File::Spec::Functions: '0'
  File::Which: '0'
  FindBin: '0'
  IO::File: '0'
  Module::Build: '0'
  TAP::Formatter::Color: '0'
  TAP::Formatter::Console: '0'
  TAP::Harness: '0'
  Text::Template: '1.44'
  URI: '0'
  perl: v5.6.1
  version: '0.77'
dynamic_config: 0
generated_by: 'Module::Build version 0.4224, CPAN::Meta::Converter version 2.150010'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Win32-CommandLine
no_index:
  directory:
    - eg
    - extras
    - notes
    - inc
    - t
    - xt
  file:
    - README.mkd
provides:
  Win32::CommandLine:
    file: lib/Win32/CommandLine.pm
    version: '0.954'
recommends:
  Win32: '0'
  Win32::Security::SID: '0'
  Win32::TieRegistry: '0'
requires:
  Carp::Assert: '0'
  File::Which: '0'
  Pod::Usage: '1.30'
  perl: v5.8.8
  version: '0.74'
resources:
  bugtracker: https://github.com/rivy/perl.Win32-CommandLine/issues
  homepage: https://github.com/rivy/perl.Win32-CommandLine
  license: http://www.perlfoundation.org/artistic_license_2_0
  repository: git://github.com/rivy/perl.Win32-CommandLine.git
version: '0.954'
x_authority: cpan:RIVY
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
